# This is a basic workflow to help you get started with Actions

name: CI

permissions:
  contents: write

# Controls when the workflow will run
on:
  push:
    tags:
      - "v*.*.*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build
        run: echo ${{ github.sha }} > Release1.txt
      - name: Test
        run: cat Release1.txt
      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: Release1.txt
